# Generated by Django 4.0.1 on 2022-01-27 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_meal_date_alter_meal_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='time',
            field=models.TimeField(),
        ),
    ]
