# Generated by Django 4.0.1 on 2022-02-07 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_meal_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Glucose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('glucose_level', models.IntegerField()),
                ('notes', models.TextField(blank=True)),
            ],
        ),
    ]
