# Generated by Django 4.0.1 on 2022-02-07 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_glucose_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='glucose',
            old_name='glucose_level',
            new_name='glucose',
        ),
    ]
