# Generated by Django 4.0.1 on 2022-02-11 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_glucose_level_glucose_glucose'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fitness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('workout_type', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
    ]
