# Generated by Django 4.0.1 on 2022-02-11 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_fitness_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fitness',
            name='time',
        ),
        migrations.AddField(
            model_name='fitness',
            name='duration',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
