# Generated by Django 4.0.1 on 2022-02-11 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_fitness_time_fitness_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='MyHappyGlucose123', max_length=30),
            preserve_default=False,
        ),
    ]
